### ISSUE TITLE
Returning data from call

### ISSUE THREAD

**Issue by AndrewMacNaughton** [bitkompagniet/housecall#3]
Hi There.
I am trying to get the data from the call. 
I currently have 
`this.queue.push(() => this.apiRequest.request(request, nocache))`

But I can't return the data from the request. I know i can use .then() to access the data once its completed running, but i need to return the 3rd party api data back out my API. Is that part of the scope of this project?

**Comment by kparkov** [comment]
I am not sure I am understanding this correctly, but it is true that it returns a promise. The only way to get out of the `.then` chain is to provide your code with a callback that is called upon completion. That is the "old fashioned" JS way of doing it.

```javascript
function(callback) {
  this.queue.push(() => this.apiRequest.request(request, nocache).then(() => callback(response));
}
```
